// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haxduiibwxlolflkrjuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheGR1aWlid3hsb2xmbGtyanV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzI5MDEsImV4cCI6MjA3Mjc0ODkwMX0.OclNVlvZu_Uyh2e0wxJpeWZuAGClVERmsF49lDO3OvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});